micronaut:
  application:
    name: tt-services
  server:
    port: 8080

datasources:
  default:
    url: ${DATASOURCES_DEFAULT_URL:`jdbc:sqlite:file:oddlabs?mode=memory&cache=shared`}
    driver-class-name: ${DATASOURCES_DEFAULT_DRIVER:org.sqlite.JDBC}
    username: ${DATASOURCES_DEFAULT_USERNAME:}
    password: ${DATASOURCES_DEFAULT_PASSWORD:}
    schema-generate: NONE

flyway:
  datasources:
    default:
      enabled: ${FLYWAY_DATASOURCES_DEFAULT_ENABLED:true}
      clean-schema: false
